name: "Release Action"
description: "Build and release binaries and Docker images"
inputs:
  tag:
    description: "Tag to release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.4"

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Set variables
      id: variables
      shell: bash
      run: |
        git_tag_name="${{ inputs.tag }}"
        # Remove refs/tags/ prefix if present
        git_tag_name="${git_tag_name#refs/tags/}"
        echo "git_tag_name=${git_tag_name}" >> $GITHUB_OUTPUT
        git_tag_name="${git_tag_name#v}"
        echo "release_tag_patch=${git_tag_name}" >> $GITHUB_OUTPUT
        echo "release_tag_minor=${git_tag_name%.*}" >> $GITHUB_OUTPUT
        echo "release_tag_major=${git_tag_name%%.*}" >> $GITHUB_OUTPUT
        echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.variables.outputs.release_tag_patch }}
          ghcr.io/${{ github.repository }}:${{ steps.variables.outputs.release_tag_minor }}
          ghcr.io/${{ github.repository }}:${{ steps.variables.outputs.release_tag_major }}
