name: Publish Docker image
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
    - '**.md'

env:
  DOCKER_BASE_NAME: ghcr.io/${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build base image
        run: |
          docker build -t "${DOCKER_BASE_NAME}:latest" .

      - name: Login
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u yuuki --password-stdin

      - name: Push to GitHub Packages
        if: github.event_name != 'pull_request'
        run: docker push "${DOCKER_BASE_NAME}:latest"
